### ISSUE TITLE
Why does version 2 not support Map anymore?

### ISSUE THREAD

**Issue by dust-0x7f** [jucardi/go-streams#14]
Why does version 2 not support Map anymore?
I'm really looking forward to using map operations in version 2!
eg
```code
func main() {
	streams.From[int]([]int{1,2,3,4,5,6}).Map[int,int](func(item int) int{
		return item * 2
	})
}
```

**Comment by ac-yingyaoyao** [comment]
Sorry, I learned that this is because go's generic types don't support the stream pattern
