### ISSUE TITLE
Missing v2 tag in go.mod

### ISSUE THREAD

**Issue by a-ryoo** [jucardi/go-streams#5]
Hi, great lib! Could you please add version 2 definition in go.mod?

Cannot import module with generics:
github.com/jucardi/go-streams@v2.0.0: invalid version: module contains a go.mod file, so module path must match major version ("github.com/jucardi/go-streams/v2")

Thanks in advance

**Comment by aveekroychowdhury** [comment]
Need this too... please add v2

**Comment by jucardi** [comment]
Done! Apologies for the delay, didn't realize my notifications were off
