### ISSUE TITLE
invalid operation: cannot index streams.From 

### ISSUE THREAD

**Issue by agentgonzo** [jucardi/go-streams#8]
I'm getting the following error when I try the sample code:
```go 
var fruitArray = []string{"peach", "apple", "pear", "plum", "pineapple", "banana", "kiwi", "orange"}
	fruitsThatStartWithP := streams.

		// Creates a stream from the given array
		From[string](fruitArray).

		// Adds a filter for strings that start with 'p'
		Filter(func(v string) bool {
			return strings.HasPrefix(v, "p")
		}).

		// Sorts alphabetically
		//Sort(strings.Compare).

		// Converts back to an array
		ToArray()
```

`invalid operation: cannot index streams.From (value of type func(set interface{}, threads ...int) streams.IStream)`

Go 1.20.2 on Ubuntu.

If I change `From[string]` to just `From`, then that particular error goes away.... but then I also have to change `func v string` to `func (v interface{})`

**Comment by jucardi** [comment]
Are you sure you are using V2? I just wrote a test and it works just fine. Given the error and the fact that you can use `From` without a generic arg, it seems that you are using V1 before generics support was added. Make sure you are doing the following to pull the dependency

```
go get github.com/jucardi/go-streams/v2@latest
```
