### ISSUE TITLE
要是 支持 err 就好了，这样就更顺畅了

### ISSUE THREAD

**Issue by erkesi** [jucardi/go-streams#9]
![image](https://user-images.githubusercontent.com/102900011/231985296-0db05f31-44cf-4a71-aeb2-85a66d58487a.png)

**Comment by erkesi** [comment]
![image](https://user-images.githubusercontent.com/102900011/231985229-5fe14e11-9780-463a-94a2-b8fbb73398c7.png)

**Comment by jucardi** [comment]
Hi @erkesi , not sure what you're attempting to report here, could you provide more details?

**Comment by jucardi** [comment]
Closing this issue due to lack of context
